name: yellowhouseproject
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c3053'
    - '#fcfaed'
    - '#f1a502'
    - '#ba1b00'
    - '#b86700'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
